/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package ems;

import hashtables.EmployeeInfo;
import hashtables.FullTimeEmployee;
import hashtables.Gender;
import hashtables.Location;
import hashtables.MyHashTable;
import hashtables.PartTimeEmployee;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ani
 */
public class JFrame extends javax.swing.JFrame {
    
    String fN, lN, currentPage;
    Gender gender;
    private MyHashTable myHT;
    int empNum;
    Location location;
    double deductRate, hourlyWage, hoursPerWeek, weeksPerYear;
    
    int yearlySalary;//
    //ihategithub<3
    
    
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        myHT = new MyHashTable(2);
        
        myHT.readFromFile();
        clear();
        welcomePanel.setVisible(true);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        locationGroup = new javax.swing.ButtonGroup();
        employmentStatus = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        sidePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addButton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        viewButton = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        fNInfoField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lNInfoField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        deductInfoField = new javax.swing.JTextField();
        maleInfoRadioButton = new javax.swing.JRadioButton();
        femaleInfoRadioButton = new javax.swing.JRadioButton();
        otherInfoRadioButton = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        missInfoRadioButton = new javax.swing.JRadioButton();
        brampInfoRadioButton = new javax.swing.JRadioButton();
        torontoInfoRadioButton = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        partTimeInfoRadioButton = new javax.swing.JRadioButton();
        fullTimeInfoRadioButton = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        hourlyWageInfoField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        hoursPerWeekInfoField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        weeksPerYearInfoField = new javax.swing.JTextField();
        yearlySalaryInfoField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        searchChoiceParent = new javax.swing.JPanel();
        preEdit = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        duringEdit = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        employeeSearchField = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        partTimePanel = new javax.swing.JPanel();
        addPTEmployeeButton = new javax.swing.JButton();
        hourlyWageFeild = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        hourlyWageField = new javax.swing.JLabel();
        hoursPerWeekField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        weeksPerYearField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        fullTimePanel = new javax.swing.JPanel();
        addFTEmployeeButton = new javax.swing.JButton();
        yearlySalaryField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        viewPanel = new javax.swing.JPanel();
        View = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        fNField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lNField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        empNumField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        deductField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        otherRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        missRadioButton = new javax.swing.JRadioButton();
        brampRadioButton = new javax.swing.JRadioButton();
        torontoRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        addContinueButton = new javax.swing.JButton();
        partTimeRadioButton = new javax.swing.JRadioButton();
        fullTimeRadioButton = new javax.swing.JRadioButton();
        welcomePanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        sidePanel.setBackground(new java.awt.Color(153, 0, 102));

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html>Employee<br>Management<br>System</html>");

        addButton.setBackground(new java.awt.Color(153, 0, 102));
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADD");

        javax.swing.GroupLayout addButtonLayout = new javax.swing.GroupLayout(addButton);
        addButton.setLayout(addButtonLayout);
        addButtonLayout.setHorizontalGroup(
            addButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addButtonLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addButtonLayout.setVerticalGroup(
            addButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        searchButton.setBackground(new java.awt.Color(153, 0, 102));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SEARCH");

        javax.swing.GroupLayout searchButtonLayout = new javax.swing.GroupLayout(searchButton);
        searchButton.setLayout(searchButtonLayout);
        searchButtonLayout.setHorizontalGroup(
            searchButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchButtonLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchButtonLayout.setVerticalGroup(
            searchButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        viewButton.setBackground(new java.awt.Color(153, 0, 102));
        viewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewButtonMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("VIEW");

        javax.swing.GroupLayout viewButtonLayout = new javax.swing.GroupLayout(viewButton);
        viewButton.setLayout(viewButtonLayout);
        viewButtonLayout.setHorizontalGroup(
            viewButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewButtonLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewButtonLayout.setVerticalGroup(
            viewButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parentPanel.setBackground(new java.awt.Color(255, 255, 255));
        parentPanel.setLayout(new java.awt.CardLayout());

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel.setPreferredSize(new java.awt.Dimension(418, 418));

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));

        fNInfoField.setEditable(false);
        fNInfoField.setBorder(null);
        fNInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNInfoFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("First Name:");

        lNInfoField.setEditable(false);
        lNInfoField.setBorder(null);
        lNInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNInfoFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("Last Name:");

        jLabel18.setText("Deduct Rate:");

        deductInfoField.setEditable(false);
        deductInfoField.setText("0");
        deductInfoField.setBorder(null);
        deductInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductInfoFieldActionPerformed(evt);
            }
        });

        genderGroup.add(maleInfoRadioButton);
        maleInfoRadioButton.setText("Male");
        maleInfoRadioButton.setEnabled(false);
        maleInfoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleInfoRadioButtonActionPerformed(evt);
            }
        });

        genderGroup.add(femaleInfoRadioButton);
        femaleInfoRadioButton.setText("Female");
        femaleInfoRadioButton.setEnabled(false);
        femaleInfoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleInfoRadioButtonActionPerformed(evt);
            }
        });

        genderGroup.add(otherInfoRadioButton);
        otherInfoRadioButton.setText("Other");
        otherInfoRadioButton.setEnabled(false);
        otherInfoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherInfoRadioButtonActionPerformed(evt);
            }
        });

        jLabel19.setText("Gender:");

        locationGroup.add(missInfoRadioButton);
        missInfoRadioButton.setText("Mississauga");
        missInfoRadioButton.setEnabled(false);
        missInfoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missInfoRadioButtonActionPerformed(evt);
            }
        });

        locationGroup.add(brampInfoRadioButton);
        brampInfoRadioButton.setText("Brampton");
        brampInfoRadioButton.setEnabled(false);
        brampInfoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brampInfoRadioButtonActionPerformed(evt);
            }
        });

        locationGroup.add(torontoInfoRadioButton);
        torontoInfoRadioButton.setText("Toronto");
        torontoInfoRadioButton.setEnabled(false);
        torontoInfoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torontoInfoRadioButtonActionPerformed(evt);
            }
        });

        jLabel20.setText("Location:");

        employmentStatus.add(partTimeInfoRadioButton);
        partTimeInfoRadioButton.setText("Part Time Employee");
        partTimeInfoRadioButton.setEnabled(false);
        partTimeInfoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeInfoRadioButtonActionPerformed(evt);
            }
        });

        employmentStatus.add(fullTimeInfoRadioButton);
        fullTimeInfoRadioButton.setText("Full Time Employee");
        fullTimeInfoRadioButton.setEnabled(false);
        fullTimeInfoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeInfoRadioButtonActionPerformed(evt);
            }
        });

        jLabel28.setText("Hourly Wage:");
        jLabel28.setToolTipText("");

        hourlyWageInfoField.setEditable(false);
        hourlyWageInfoField.setText("0");
        hourlyWageInfoField.setBorder(null);
        hourlyWageInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyWageInfoFieldActionPerformed(evt);
            }
        });

        jLabel29.setText("Hours per Week:");

        hoursPerWeekInfoField.setEditable(false);
        hoursPerWeekInfoField.setText("0");
        hoursPerWeekInfoField.setBorder(null);
        hoursPerWeekInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursPerWeekInfoFieldActionPerformed(evt);
            }
        });

        jLabel30.setText("Weeks per Year:");

        weeksPerYearInfoField.setEditable(false);
        weeksPerYearInfoField.setText("0");
        weeksPerYearInfoField.setBorder(null);
        weeksPerYearInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeksPerYearInfoFieldActionPerformed(evt);
            }
        });

        yearlySalaryInfoField.setEditable(false);
        yearlySalaryInfoField.setText("0");
        yearlySalaryInfoField.setBorder(null);
        yearlySalaryInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlySalaryInfoFieldActionPerformed(evt);
            }
        });

        jLabel31.setText("Yearly Salary:");

        searchChoiceParent.setLayout(new java.awt.CardLayout());

        preEdit.setBackground(new java.awt.Color(255, 255, 255));

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout preEditLayout = new javax.swing.GroupLayout(preEdit);
        preEdit.setLayout(preEditLayout);
        preEditLayout.setHorizontalGroup(
            preEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preEditLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        preEditLayout.setVerticalGroup(
            preEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(preEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(removeButton))
                .addGap(17, 17, 17))
        );

        searchChoiceParent.add(preEdit, "card4");

        duringEdit.setBackground(new java.awt.Color(255, 255, 255));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout duringEditLayout = new javax.swing.GroupLayout(duringEdit);
        duringEdit.setLayout(duringEditLayout);
        duringEditLayout.setHorizontalGroup(
            duringEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(duringEditLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        duringEditLayout.setVerticalGroup(
            duringEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, duringEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(duringEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(17, 17, 17))
        );

        searchChoiceParent.add(duringEdit, "card3");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchChoiceParent, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(425, 425, 425))
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deductInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearlySalaryInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weeksPerYearInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourlyWageInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursPerWeekInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(missInfoRadioButton)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(femaleInfoRadioButton)
                            .addComponent(maleInfoRadioButton)
                            .addComponent(otherInfoRadioButton)
                            .addComponent(fullTimeInfoRadioButton)
                            .addComponent(partTimeInfoRadioButton)))
                    .addComponent(torontoInfoRadioButton)
                    .addComponent(brampInfoRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fNInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(brampInfoRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lNInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missInfoRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(torontoInfoRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deductInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleInfoRadioButton)
                    .addComponent(jLabel28)
                    .addComponent(jLabel19)
                    .addComponent(hourlyWageInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(femaleInfoRadioButton)
                    .addComponent(hoursPerWeekInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(otherInfoRadioButton)
                    .addComponent(weeksPerYearInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(yearlySalaryInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(fullTimeInfoRadioButton)
                        .addGap(3, 3, 3)
                        .addComponent(partTimeInfoRadioButton)
                        .addGap(18, 18, 18)))
                .addComponent(searchChoiceParent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Employee Number:");

        employeeSearchField.setBorder(null);
        employeeSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(employeeSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        parentPanel.add(searchPanel, "card3");

        partTimePanel.setBackground(new java.awt.Color(255, 255, 255));

        addPTEmployeeButton.setText("Add Employee");
        addPTEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPTEmployeeButtonActionPerformed(evt);
            }
        });

        hourlyWageFeild.setBorder(null);
        hourlyWageFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyWageFeildActionPerformed(evt);
            }
        });

        hourlyWageField.setText("Hourly Wage");

        hoursPerWeekField.setBorder(null);
        hoursPerWeekField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursPerWeekFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Hours per Week");

        weeksPerYearField.setBorder(null);
        weeksPerYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeksPerYearFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Weeks per Year");

        javax.swing.GroupLayout partTimePanelLayout = new javax.swing.GroupLayout(partTimePanel);
        partTimePanel.setLayout(partTimePanelLayout);
        partTimePanelLayout.setHorizontalGroup(
            partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, partTimePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPTEmployeeButton)
                .addGap(18, 18, 18))
            .addGroup(partTimePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hourlyWageField)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourlyWageFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        partTimePanelLayout.setVerticalGroup(
            partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, partTimePanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hourlyWageFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hourlyWageField))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(partTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(addPTEmployeeButton)
                .addGap(14, 14, 14))
        );

        parentPanel.add(partTimePanel, "card4");

        fullTimePanel.setBackground(new java.awt.Color(255, 255, 255));

        addFTEmployeeButton.setText("Add Employee");
        addFTEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFTEmployeeButtonActionPerformed(evt);
            }
        });

        yearlySalaryField.setBorder(null);
        yearlySalaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlySalaryFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Yearly Salary");

        javax.swing.GroupLayout fullTimePanelLayout = new javax.swing.GroupLayout(fullTimePanel);
        fullTimePanel.setLayout(fullTimePanelLayout);
        fullTimePanelLayout.setHorizontalGroup(
            fullTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fullTimePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addFTEmployeeButton)
                .addGap(18, 18, 18))
            .addGroup(fullTimePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fullTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearlySalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        fullTimePanelLayout.setVerticalGroup(
            fullTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fullTimePanelLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(fullTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fullTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yearlySalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(addFTEmployeeButton)
                .addGap(14, 14, 14))
        );

        parentPanel.add(fullTimePanel, "card5");

        viewPanel.setBackground(new java.awt.Color(255, 255, 255));

        View.setText("Refresh");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Empl. #", "Type"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        title.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        title.setText("Employee Information");

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(View))
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(View)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        parentPanel.add(viewPanel, "card6");

        addPanel.setBackground(new java.awt.Color(255, 255, 255));

        fNField.setBorder(null);
        fNField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name:");

        lNField.setBorder(null);
        lNField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Last Name:");

        empNumField.setText("000000");
        empNumField.setBorder(null);
        empNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Employee #:");

        deductField.setText("0");
        deductField.setBorder(null);
        deductField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Deduct Rate:");

        genderGroup.add(maleRadioButton);
        maleRadioButton.setText("Male");
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });

        genderGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");
        femaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonActionPerformed(evt);
            }
        });

        genderGroup.add(otherRadioButton);
        otherRadioButton.setText("Other");
        otherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherRadioButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Gender:");

        locationGroup.add(missRadioButton);
        missRadioButton.setText("Mississauga");
        missRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missRadioButtonActionPerformed(evt);
            }
        });

        locationGroup.add(brampRadioButton);
        brampRadioButton.setText("Brampton");
        brampRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brampRadioButtonActionPerformed(evt);
            }
        });

        locationGroup.add(torontoRadioButton);
        torontoRadioButton.setText("Toronto");
        torontoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torontoRadioButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Location:");

        addContinueButton.setText("Continue");
        addContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContinueButtonActionPerformed(evt);
            }
        });

        employmentStatus.add(partTimeRadioButton);
        partTimeRadioButton.setText("Part Time Employee");
        partTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeRadioButtonActionPerformed(evt);
            }
        });

        employmentStatus.add(fullTimeRadioButton);
        fullTimeRadioButton.setText("Full Time Employee");
        fullTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fNField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deductField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(188, 188, 188))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(femaleRadioButton)
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addComponent(maleRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addComponent(otherRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(missRadioButton)
                                    .addComponent(brampRadioButton)
                                    .addComponent(torontoRadioButton)))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(partTimeRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(fullTimeRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addContinueButton)))))
                .addGap(12, 12, 12))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(empNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deductField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(maleRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femaleRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherRadioButton))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(missRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brampRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(torontoRadioButton)))
                .addGap(18, 18, 18)
                .addComponent(partTimeRadioButton)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullTimeRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(addContinueButton)
                        .addGap(14, 14, 14))))
        );

        parentPanel.add(addPanel, "card2");

        welcomePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("<html><div style='text-align: center;'>Welcome to your<br> Employee Management System</div></html>");

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel24.setText("Hit the Add button to get started");

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel24)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jLabel24)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        parentPanel.add(welcomePanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void fNFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNFieldActionPerformed
    
    private void lNFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNFieldActionPerformed
    
    private void empNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumFieldActionPerformed
    
    private void deductFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deductFieldActionPerformed
    
    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:
        gender = Gender.MALE;
    }//GEN-LAST:event_maleRadioButtonActionPerformed
    
    private void missRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missRadioButtonActionPerformed
        // TODO add your handling code here:
        location = Location.MISSISSAUGA;
    }//GEN-LAST:event_missRadioButtonActionPerformed
    
    private void partTimeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeRadioButtonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_partTimeRadioButtonActionPerformed
    
    private void fullTimeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullTimeRadioButtonActionPerformed
                    
    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:
        clear();
        addPanel.setVisible(true);
        currentPage = "add";
    }//GEN-LAST:event_addButtonMouseClicked
    
    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        clear();
        searchPanel.setVisible(true);
        currentPage = "remove";
    }//GEN-LAST:event_searchButtonMouseClicked
    
    private void addPTEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPTEmployeeButtonActionPerformed
        // TODO add your handling code here:
        hourlyWage = Double.parseDouble(hourlyWageFeild.getText());
        hoursPerWeek = Double.parseDouble(hoursPerWeekField.getText());
        weeksPerYear = Double.parseDouble(weeksPerYearField.getText());
        PartTimeEmployee someEmployee = new PartTimeEmployee(empNum, fN, lN, gender, location, deductRate, hourlyWage, hoursPerWeek, weeksPerYear);
        System.out.println(someEmployee.getEmpNumber());
        myHT.addEmployee(someEmployee);
        JOptionPane.showMessageDialog(null, "Employee Added!");
        
        clear();
        viewPanel.setVisible(true);
        String type = null;
        DefaultTableModel pte = (DefaultTableModel) jTable1.getModel();
        pte.getDataVector().removeAllElements();
        ArrayList<EmployeeInfo> employees = new ArrayList();
        myHT.displayToTable (employees);
        int length = employees.size();
        for (int i = 0; i < length; i++ ) {
            String fn = employees.get(i).getFirstName();
            String ln = employees.get(i).getLastName();
            int empn = employees.get(i).getEmpNumber();
            if (employees.get(i) instanceof PartTimeEmployee) {
                type = "Part Time";
            } else if (employees.get(i) instanceof FullTimeEmployee) {
                type = "Full Time";
            }
            pte.addRow(new Object[]{fn, ln, empn, type});
        
        }
    }//GEN-LAST:event_addPTEmployeeButtonActionPerformed
    
    private void hourlyWageFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyWageFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyWageFeildActionPerformed
    
    private void hoursPerWeekFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursPerWeekFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursPerWeekFieldActionPerformed
    
    private void weeksPerYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeksPerYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeksPerYearFieldActionPerformed
    
    private void addContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContinueButtonActionPerformed
        // TODO add your handling code here:
        fN = fNField.getText();
        lN = lNField.getText();
        empNum = Integer.parseInt(empNumField.getText());
        deductRate = Double.parseDouble(deductField.getText());
        
        addPanel.setVisible(false);
        if (fullTimeRadioButton.isSelected()) {
            clear();
            fullTimePanel.setVisible(true);
        } else if (partTimeRadioButton.isSelected()) {
            clear();
            partTimePanel.setVisible(true);
        }
    }//GEN-LAST:event_addContinueButtonActionPerformed
    
    private void otherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherRadioButtonActionPerformed
        // TODO add your handling code here:
        gender = Gender.OTHER;
        
    }//GEN-LAST:event_otherRadioButtonActionPerformed
    
    private void femaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonActionPerformed
        // TODO add your handling code here:
        gender = Gender.FEMALE;
    }//GEN-LAST:event_femaleRadioButtonActionPerformed
    
    private void brampRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brampRadioButtonActionPerformed
        // TODO add your handling code here:
        location = Location.BRAMPTON;
    }//GEN-LAST:event_brampRadioButtonActionPerformed
    
    private void torontoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torontoRadioButtonActionPerformed
        // TODO add your handling code here:
        location = Location.TORONTO;
    }//GEN-LAST:event_torontoRadioButtonActionPerformed
    
    private void addFTEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFTEmployeeButtonActionPerformed
        
        yearlySalary = Integer.parseInt(yearlySalaryField.getText());
        FullTimeEmployee someEmployee = new FullTimeEmployee(empNum, fN, lN, gender, location, deductRate, yearlySalary);
        myHT.addEmployee(someEmployee);
        JOptionPane.showMessageDialog(null, "Employee Successfully Added");
        
        clear();
        viewPanel.setVisible(true);
        String type = null;
        DefaultTableModel pte = (DefaultTableModel) jTable1.getModel();
        pte.getDataVector().removeAllElements();
        ArrayList<EmployeeInfo> employees = new ArrayList();
        myHT.displayToTable (employees);
        int length = employees.size();
        for (int i = 0; i < length; i++ ) {
            String fn = employees.get(i).getFirstName();
            String ln = employees.get(i).getLastName();
            int empn = employees.get(i).getEmpNumber();
            if (employees.get(i) instanceof PartTimeEmployee) {
                type = "Part Time";
            } else if (employees.get(i) instanceof FullTimeEmployee) {
                type = "Full Time";
            }
            pte.addRow(new Object[]{fn, ln, empn, type});
        
        }
    }//GEN-LAST:event_addFTEmployeeButtonActionPerformed
    
    private void yearlySalaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlySalaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearlySalaryFieldActionPerformed
    
    private void viewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewButtonMouseClicked
        // TODO add your handling code here:
        clear();
        viewPanel.setVisible(true);
        String type = null;
        DefaultTableModel pte = (DefaultTableModel) jTable1.getModel();
        pte.getDataVector().removeAllElements();
        ArrayList<EmployeeInfo> employees = new ArrayList();
        myHT.displayToTable (employees);
        int length = employees.size();
        for (int i = 0; i < length; i++ ) {
            String fn = employees.get(i).getFirstName();
            String ln = employees.get(i).getLastName();
            int empn = employees.get(i).getEmpNumber();
            if (employees.get(i) instanceof PartTimeEmployee) {
                type = "Part Time";
            } else if (employees.get(i) instanceof FullTimeEmployee) {
                type = "Full Time";
            }
            pte.addRow(new Object[]{fn, ln, empn, type});
        
        }
    }//GEN-LAST:event_viewButtonMouseClicked
            
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        myHT.writeToFile();
        System.out.println();
    }//GEN-LAST:event_formWindowClosing
                                                                                
    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        String type = null;
        DefaultTableModel pte = (DefaultTableModel) jTable1.getModel();
        pte.getDataVector().removeAllElements();
        ArrayList<EmployeeInfo> employees = new ArrayList();
        myHT.displayToTable (employees);
        int length = employees.size();
        for (int i = 0; i < length; i++ ) {
            String fn = employees.get(i).getFirstName();
            String ln = employees.get(i).getLastName();
            int empn = employees.get(i).getEmpNumber();
            if (employees.get(i) instanceof PartTimeEmployee) {
                type = "Part Time";
            } else if (employees.get(i) instanceof FullTimeEmployee) {
                type = "Full Time";
            }
            pte.addRow(new Object[]{fn, ln, empn, type});
        }
    }//GEN-LAST:event_ViewActionPerformed

    private void employeeSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSearchFieldActionPerformed
        // TODO add your handling code here:
        int toFind = Integer.parseInt(employeeSearchField.getText());
        EmployeeInfo found = null;
        found = myHT.search(toFind);

        if (found == null){
            JOptionPane.showMessageDialog(null, "No Employee Found");
        } else {
            fNInfoField.setText(found.getFirstName());
            lNInfoField.setText(found.getLastName());
            deductInfoField.setText(Integer.toString((int) found.getDeductRate()));

            if(found instanceof PartTimeEmployee){
                partTimeInfoRadioButton.setSelected(true);

                hoursPerWeekInfoField.setText(Double.toString(((PartTimeEmployee) found).getHoursPerWeek()));
                hoursPerWeekInfoField.setEditable(false);
                hourlyWageInfoField.setText(Double.toString(((PartTimeEmployee) found).getHourlyWage()));
                hourlyWageInfoField.setEditable(false);
                weeksPerYearInfoField.setText(Double.toString(((PartTimeEmployee) found).getWeeksPerYear()));
                weeksPerYearInfoField.setEditable(false);
                yearlySalaryInfoField.setEnabled(false);

            } else if (found instanceof FullTimeEmployee){
                fullTimeInfoRadioButton.setSelected(true);
                yearlySalaryInfoField.setText(Double.toString(((FullTimeEmployee) found).AnnualGrossIncome()));

                weeksPerYearInfoField.setEnabled(false);
                hourlyWageInfoField.setEnabled(false);
                hoursPerWeekInfoField.setEnabled(false);
            }

            if (found.getGender() == Gender.MALE){
                maleInfoRadioButton.setSelected(true);
            } else if(found.getGender() == Gender.FEMALE){
                femaleInfoRadioButton.setSelected(true);
            } else if(found.getGender() == Gender.OTHER){
                otherInfoRadioButton.setSelected(true);
            }

            if (found.getLocation() == Location.BRAMPTON){
                brampInfoRadioButton.setSelected(true);
            } else if (found.getLocation() == Location.MISSISSAUGA){
                missInfoRadioButton.setSelected(true);
            } else if (found.getLocation() == Location.TORONTO){
                torontoInfoRadioButton.setSelected(true);
            }

            infoPanel.setVisible(true);
        }
    }//GEN-LAST:event_employeeSearchFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        myHT.removeEmployee(myHT.search(Integer.parseInt(employeeSearchField.getText())));
        fN = fNInfoField.getText();
        lN = lNInfoField.getText();
        empNum = Integer.parseInt(employeeSearchField.getText());
        deductRate = Double.parseDouble(deductInfoField.getText());
        if (partTimeInfoRadioButton.isSelected()){
            hourlyWage = Double.parseDouble(hourlyWageInfoField.getText());
            hoursPerWeek = Double.parseDouble(hoursPerWeekInfoField.getText());
            weeksPerYear = Double.parseDouble(weeksPerYearInfoField.getText());
            PartTimeEmployee someEmployee = new PartTimeEmployee(empNum, fN, lN, gender, location, deductRate, hourlyWage, hoursPerWeek, weeksPerYear);
            System.out.println(someEmployee.getEmpNumber());
            myHT.addEmployee(someEmployee);
        } else if (fullTimeInfoRadioButton.isSelected()){
            myHT.addEmployee(new FullTimeEmployee(this.empNum,this.fN, this.lN, this.gender,  this.location,
                this.deductRate,Integer.parseInt(yearlySalaryInfoField.getText())));
        }
        JOptionPane.showMessageDialog(null, "Employee Edited!");

        fNInfoField.setEditable(false);
        lNInfoField.setEditable(false);
        deductInfoField.setEditable(false);
        hourlyWageInfoField.setEditable(false);
        hoursPerWeekInfoField.setEditable(false);
        weeksPerYearInfoField.setEditable(false);
        yearlySalaryInfoField.setEditable(false);
        maleInfoRadioButton.setEnabled(false);
        maleInfoRadioButton.setEnabled(false);
        femaleInfoRadioButton.setEnabled(false);
        otherInfoRadioButton.setEnabled(false);
        missInfoRadioButton.setEnabled(false);
        brampInfoRadioButton.setEnabled(false);
        torontoInfoRadioButton.setEnabled(false);
        partTimeInfoRadioButton.setEnabled(false);
        fullTimeInfoRadioButton.setEnabled(false);

        duringEdit.setVisible(false);
        preEdit.setVisible(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:v

        int toFind = Integer.parseInt(employeeSearchField.getText());
        EmployeeInfo found = null;
        found = myHT.search(toFind);

        fNInfoField.setText(found.getFirstName());
        lNInfoField.setText(found.getLastName());
        deductInfoField.setText(Integer.toString((int) found.getDeductRate()));
        hoursPerWeekInfoField.setText("");
        hourlyWageInfoField.setText("");
        weeksPerYearInfoField.setText("");
        yearlySalaryInfoField.setText("");

        if(found instanceof PartTimeEmployee){
            partTimeInfoRadioButton.setSelected(true);

            hoursPerWeekInfoField.setText(Double.toString(((PartTimeEmployee) found).getHoursPerWeek()));
            hoursPerWeekInfoField.setEditable(false);
            hourlyWageInfoField.setText(Double.toString(((PartTimeEmployee) found).getHourlyWage()));
            hourlyWageInfoField.setEditable(false);
            weeksPerYearInfoField.setText(Double.toString(((PartTimeEmployee) found).getWeeksPerYear()));
            weeksPerYearInfoField.setEditable(false);

        } else if (found instanceof FullTimeEmployee){
            fullTimeInfoRadioButton.setSelected(true);
            yearlySalaryInfoField.setText(Double.toString(((FullTimeEmployee) found).AnnualGrossIncome()));
        }

        if (found.getGender() == Gender.MALE){
            maleInfoRadioButton.setSelected(true);
        } else if(found.getGender() == Gender.FEMALE){
            femaleInfoRadioButton.setSelected(true);
        } else if(found.getGender() == Gender.OTHER){
            otherInfoRadioButton.setSelected(true);
        }

        if (found.getLocation() == Location.BRAMPTON){
            brampInfoRadioButton.setSelected(true);
        } else if (found.getLocation() == Location.MISSISSAUGA){
            missInfoRadioButton.setSelected(true);
        } else if (found.getLocation() == Location.TORONTO){
            torontoInfoRadioButton.setSelected(true);
        }

        fNInfoField.setEditable(false);
        lNInfoField.setEditable(false);
        deductInfoField.setEditable(false);
        hourlyWageInfoField.setEditable(false);
        hoursPerWeekInfoField.setEditable(false);
        weeksPerYearInfoField.setEditable(false);
        yearlySalaryInfoField.setEditable(false);
        maleInfoRadioButton.setEnabled(false);
        maleInfoRadioButton.setEnabled(false);
        femaleInfoRadioButton.setEnabled(false);
        otherInfoRadioButton.setEnabled(false);
        missInfoRadioButton.setEnabled(false);
        brampInfoRadioButton.setEnabled(false);
        torontoInfoRadioButton.setEnabled(false);
        partTimeInfoRadioButton.setEnabled(false);
        fullTimeInfoRadioButton.setEnabled(false);

        preEdit.setVisible(true);
        duringEdit.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        int toRemove = Integer.parseInt(employeeSearchField.getText());
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?");
        if (response == JOptionPane.YES_OPTION){
            myHT.removeEmployee(myHT.search(toRemove));
            JOptionPane.showMessageDialog(null, "The employee has been deleted");
            infoPanel.setVisible(false);
        } else if (response == JOptionPane.NO_OPTION || response == JOptionPane.CLOSED_OPTION || response == JOptionPane.CANCEL_OPTION) {

        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        preEdit.setVisible(false);
        duringEdit.setVisible(true);

        if (partTimeInfoRadioButton.isSelected()){
            yearlySalaryInfoField.setEnabled(false);
        } else if (fullTimeInfoRadioButton.isSelected()){
            hourlyWageInfoField.setEnabled(true);
            hoursPerWeekInfoField.setEnabled(true);
            weeksPerYearInfoField.setEnabled(true);
        }

        fNInfoField.setEditable(true);
        lNInfoField.setEditable(true);
        deductInfoField.setEditable(true);
        hourlyWageInfoField.setEditable(true);
        hoursPerWeekInfoField.setEditable(true);
        weeksPerYearInfoField.setEditable(true);
        yearlySalaryInfoField.setEditable(true);
        maleInfoRadioButton.setEnabled(true);
        maleInfoRadioButton.setEnabled(true);
        femaleInfoRadioButton.setEnabled(true);
        otherInfoRadioButton.setEnabled(true);
        missInfoRadioButton.setEnabled(true);
        brampInfoRadioButton.setEnabled(true);
        torontoInfoRadioButton.setEnabled(true);
        partTimeInfoRadioButton.setEnabled(true);
        fullTimeInfoRadioButton.setEnabled(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void yearlySalaryInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlySalaryInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearlySalaryInfoFieldActionPerformed

    private void weeksPerYearInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeksPerYearInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeksPerYearInfoFieldActionPerformed

    private void hoursPerWeekInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursPerWeekInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursPerWeekInfoFieldActionPerformed

    private void hourlyWageInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyWageInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyWageInfoFieldActionPerformed

    private void fullTimeInfoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeInfoRadioButtonActionPerformed
        // TODO add your handling code here:
        hourlyWageInfoField.setEnabled(false);
        hoursPerWeekInfoField.setEnabled(false);
        weeksPerYearInfoField.setEnabled(false);
        hourlyWageInfoField.setText("");
        hoursPerWeekInfoField.setText("");
        weeksPerYearInfoField.setText("");
        yearlySalaryInfoField.setEnabled(true);
    }//GEN-LAST:event_fullTimeInfoRadioButtonActionPerformed

    private void partTimeInfoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeInfoRadioButtonActionPerformed
        // TODO add your handling code here:
        hourlyWageInfoField.setEnabled(true);
        hoursPerWeekInfoField.setEnabled(true);
        weeksPerYearInfoField.setEnabled(true);
        yearlySalaryInfoField.setText("");
        yearlySalaryInfoField.setEnabled(false);
    }//GEN-LAST:event_partTimeInfoRadioButtonActionPerformed

    private void torontoInfoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torontoInfoRadioButtonActionPerformed
        // TODO add your handling code here:
        location = Location.TORONTO;
    }//GEN-LAST:event_torontoInfoRadioButtonActionPerformed

    private void brampInfoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brampInfoRadioButtonActionPerformed
        // TODO add your handling code here:
        location = Location.BRAMPTON;
    }//GEN-LAST:event_brampInfoRadioButtonActionPerformed

    private void missInfoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missInfoRadioButtonActionPerformed
        // TODO add your handling code here:
        location = Location.MISSISSAUGA;
    }//GEN-LAST:event_missInfoRadioButtonActionPerformed

    private void otherInfoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherInfoRadioButtonActionPerformed
        // TODO add your handling code here:
        gender = Gender.OTHER;
    }//GEN-LAST:event_otherInfoRadioButtonActionPerformed

    private void femaleInfoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleInfoRadioButtonActionPerformed
        // TODO add your handling code here:
        gender = Gender.FEMALE;
    }//GEN-LAST:event_femaleInfoRadioButtonActionPerformed

    private void maleInfoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleInfoRadioButtonActionPerformed
        // TODO add your handling code here:
        gender = Gender.MALE;
    }//GEN-LAST:event_maleInfoRadioButtonActionPerformed

    private void deductInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deductInfoFieldActionPerformed

    private void lNInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNInfoFieldActionPerformed

    private void fNInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNInfoFieldActionPerformed
    
    private void setBackground(JPanel panel){
        panel.setBackground(new Color(148, 204, 248));
    }
    
    private void resetBackground(JPanel panel) {
        panel.setBackground(new Color(100, 181, 246));
    }
    
    private void clear() {
        addPanel.setVisible(false);
        searchPanel.setVisible(false);
        partTimePanel.setVisible(false);
        fullTimePanel.setVisible(false);
        infoPanel.setVisible(false);
        viewPanel.setVisible(false);
        welcomePanel.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton View;
    private javax.swing.JPanel addButton;
    private javax.swing.JButton addContinueButton;
    private javax.swing.JButton addFTEmployeeButton;
    private javax.swing.JButton addPTEmployeeButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JRadioButton brampInfoRadioButton;
    private javax.swing.JRadioButton brampRadioButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField deductField;
    private javax.swing.JTextField deductInfoField;
    private javax.swing.JPanel duringEdit;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField empNumField;
    private javax.swing.JTextField employeeSearchField;
    private javax.swing.ButtonGroup employmentStatus;
    private javax.swing.JTextField fNField;
    private javax.swing.JTextField fNInfoField;
    private javax.swing.JRadioButton femaleInfoRadioButton;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JRadioButton fullTimeInfoRadioButton;
    private javax.swing.JPanel fullTimePanel;
    private javax.swing.JRadioButton fullTimeRadioButton;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JTextField hourlyWageFeild;
    private javax.swing.JLabel hourlyWageField;
    private javax.swing.JTextField hourlyWageInfoField;
    private javax.swing.JTextField hoursPerWeekField;
    private javax.swing.JTextField hoursPerWeekInfoField;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lNField;
    private javax.swing.JTextField lNInfoField;
    private javax.swing.ButtonGroup locationGroup;
    private javax.swing.JRadioButton maleInfoRadioButton;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton missInfoRadioButton;
    private javax.swing.JRadioButton missRadioButton;
    private javax.swing.JRadioButton otherInfoRadioButton;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JRadioButton partTimeInfoRadioButton;
    private javax.swing.JPanel partTimePanel;
    private javax.swing.JRadioButton partTimeRadioButton;
    private javax.swing.JPanel preEdit;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel searchButton;
    private javax.swing.JPanel searchChoiceParent;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel title;
    private javax.swing.JRadioButton torontoInfoRadioButton;
    private javax.swing.JRadioButton torontoRadioButton;
    private javax.swing.JPanel viewButton;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JTextField weeksPerYearField;
    private javax.swing.JTextField weeksPerYearInfoField;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JTextField yearlySalaryField;
    private javax.swing.JTextField yearlySalaryInfoField;
    // End of variables declaration//GEN-END:variables
}
